# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCopartsearch100():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_copartsearch100(self):
    self.driver.get("https://www.copart.com/")
    self.driver.set_window_size(1258, 786)
    self.driver.find_element(By.ID, "input-search").click()
    self.driver.find_element(By.ID, "input-search").send_keys("porsche")
    self.driver.find_element(By.ID, "input-search").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "serverSideDataTable_filter").click()
    self.driver.find_element(By.NAME, "serverSideDataTable_length").click()
    dropdown = self.driver.find_element(By.NAME, "serverSideDataTable_length")
    dropdown.find_element(By.XPATH, "//option[. = '100']").click()
    self.driver.find_element(By.NAME, "serverSideDataTable_length").click()
  
